<?xml version="1.0"?>

<!-- 
  * This file describes the tracks for the robot: Inspector longarm. 
  *
  * Copyright (c) 2023 taurob GmbH. All rights reserved. Confidential and proprietary.
  * Perfektastrasse 57/7, 1230 Wien, Austria. office@taurob.com
  -->

<robot name="taurob_inspector_longarm"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- [BEGIN] ===  Macro: Inspector tracks. === -->
    <xacro:macro name="inspector_tracks" params="track_length flipper_offset_x flipper_upper_shortening_x track_wheel_radius track_width track_offset_y track_offset_x track_centre_wheel_x *origin">

        <!-- [BEGIN] === Tracks: Visual and collision geometries for the .dae - tracks_side 

        [Info]  
                    We define two additional rectangles on either sides of the chassis as additional track elements. 
                    Without these elements, one would notice a gap in between flipper_link_1 and flipper_link_0 when a "flipper up"
                    motion is executed. These rectangular blocks necessarily compensate for the gap created, ensuring that the visual
                    and the collision geometries concur with the entirety of the track as seen in physicality. 

                    These elements will no longer be required in the case we, one day, have well-defined .dae files for the tracks + flippers.
                    At such a point, the whole of the block can be considered "depricated" and re-worked towards a better definition.  
                                                                                                                                                    === -->
        <!-- [BEGIN] === Visual and collision geometries for the .dae - tracks_side wheels -->   

        <!-- [BEGIN] === Joint: flipper_joint_fixed === -->
        <joint name="flipper_joint_fixed" type="fixed">
            <parent link="chassis_link"/>
            <child link="flipper_link_fixed"/>
        </joint>
        
        <!-- [BEGIN] === Link: flipper_link_fixed === -->
        <link name="flipper_link_fixed">
            <!-- Right cuboid when viewed from the back -->
            <visual>
                <origin xyz="${track_offset_x} -${track_offset_y} 0.0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://taurob_robots_description/meshes/chassis_inspector_longarm/tracks_sides.dae"/>
                </geometry>
                <material name="black">
                    <color rgba="0.027450980392156862 0.050980392156862744 0.050980392156862744 1.0"/>
                </material>
            </visual>

            <collision>
                <origin xyz="${track_offset_x} -${track_offset_y} 0.0" rpy="0 0 0"/>
                <geometry>
                    <box size="${track_offset_x*2} ${track_width} ${track_wheel_radius*2}"/>
                </geometry>
            </collision> 

            <!-- Left cuboid  when viewed from the back -->
             <visual>
                <origin xyz="${track_offset_x} ${track_offset_y} 0.0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://taurob_robots_description/meshes/chassis_inspector_longarm/tracks_sides.dae"/>
                </geometry>
                <material name="black">
                    <color rgba="0.027450980392156862 0.050980392156862744 0.050980392156862744 1.0"/>
                </material>
            </visual>

            <collision>
               <origin xyz="${track_offset_x} ${track_offset_y} 0.0" rpy="0 0 0"/>
                <geometry>
                    <box size="${track_offset_x*2} ${track_width} ${track_wheel_radius*2}"/>
                </geometry>
            </collision> 
        
            <!-- Right wheel when viewed from the back-->
            <collision>
                <origin xyz="0 -${track_offset_y} 0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
            </collision>   

            <!-- Left wheel when viewed from the back  -->
            <collision>
                <origin xyz="0 ${track_offset_y} 0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
            </collision> 
        </link>

        <!-- [BEGIN] === Joint: flipper_joint_1 === -->
        <joint name="flipper_joint_1" type="revolute">
            <xacro:insert_block name="origin"/>
            <axis xyz="0 -1 0"/>
            <mimic joint="flipper_joint" multiplier="0.66"/>
            <limit lower="${-170 * M_PI / 180}" upper="${180 * M_PI / 180}" effort="100000" velocity="${10.0 * 360 * M_PI / 180}" />
            <parent link="chassis_link"/>
            <child link="flipper_link_0"/>
        </joint>

        <!-- [BEGIN] === Link: flipper_link_0 === -->
        <link name="flipper_link_0">
            <xacro:inertial_cuboid_with_pose mass="20.0" x_length="${track_length*0.25}" y_length="${track_width*2}" z_length="0.17651">
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            </xacro:inertial_cuboid_with_pose>
            <origin xyz="0 0 0" rpy="0 0 0" />

            <visual> <!-- Front right wheel -->
                <origin xyz="${track_length-2*track_wheel_radius-flipper_upper_shortening_x} -${track_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 1"/>
                </material>
            </visual>
            
            <collision>
                <origin xyz="${track_length-2*track_wheel_radius-flipper_upper_shortening_x} -${track_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
            </collision>

            <visual> <!-- Rear right wheel -->
                <origin xyz="0 -${track_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 1"/>
                </material>
            </visual>
            
            <collision>
                <origin xyz="0 -${track_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
            </collision>

            <visual> <!-- Right track -->
                <origin xyz="${track_length*0.5-track_wheel_radius-flipper_upper_shortening_x*0.5} -${track_offset_y} 0.0" rpy="0 0 0"/>
                <geometry>
                    <box size="${track_length-2*track_wheel_radius-flipper_upper_shortening_x} ${track_width} ${track_wheel_radius*2}"/>
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 1"/>
                </material>
            </visual>
            
            <collision>
                <origin xyz="${track_length*0.5-track_wheel_radius-flipper_upper_shortening_x*0.5} -${track_offset_y} 0.0" rpy="0 0 0"/>
                <geometry>
                    <box size="${track_length-2*track_wheel_radius-flipper_upper_shortening_x} ${track_width} ${track_wheel_radius*2}"/>
                </geometry>
            </collision>

            <visual> <!-- Front left wheel-->
                <origin xyz="${track_length-2*track_wheel_radius-flipper_upper_shortening_x} ${track_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 1"/>
                </material>
            </visual>
            
            <collision>
                <origin xyz="${track_length-2*track_wheel_radius-flipper_upper_shortening_x} ${track_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
            </collision>

            <visual> <!-- Rear left wheel-->
                <origin xyz="0 ${track_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
                <material name="black">
                    <color rgba="1 1 1 1"/>
                </material>
            </visual>
            
            <collision>
                <origin xyz="0 ${track_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
            </collision>

            <visual> <!-- Left track -->
                <origin xyz="${track_length*0.5-track_wheel_radius-flipper_upper_shortening_x*0.5} ${track_offset_y} 0.0" rpy="0 0 0"/>
                <geometry>
                    <box size="${track_length-2*track_wheel_radius-flipper_upper_shortening_x} ${track_width} ${track_wheel_radius*2}"/>
                </geometry>
                <material name="black">
                    <color rgba="1 1 1 1"/>
                </material>
            </visual>

            <collision>
                <origin xyz="${track_length*0.5-track_wheel_radius-flipper_upper_shortening_x*0.5} ${track_offset_y} 0.0" rpy="0 0 0"/>
                <geometry>
                    <box size="${track_length-2*track_wheel_radius-flipper_upper_shortening_x} ${track_width} ${track_wheel_radius*2}"/>
                </geometry>
            </collision>
        </link>


        <!-- [BEGIN] === Joint: flipper_joint === -->
         <joint name="flipper_joint" type="revolute">
            <origin xyz="${track_centre_wheel_x} 0 0" rpy="0 0 0" />
            <axis xyz="0 -1 0"/>
            <limit lower="${-50 * M_PI / 180}" upper="${30 * M_PI / 180}" effort="100000" velocity="${1.0 * 30 * M_PI / 180}" />
            <parent link="chassis_link"/>
            <child link="flipper_link_1"/>
        </joint>

        <!-- [BEGIN] === Link: flipper_link_1 === -->
        <link name="flipper_link_1">
            <xacro:inertial_cuboid_with_pose mass="1.0" x_length="${track_length*0.5}" y_length="${track_width*2}" z_length="0.17651">
                <origin xyz="${track_length*0.5-track_wheel_radius*2} 0.0 0.0" rpy="0 0 0" />
            </xacro:inertial_cuboid_with_pose>
            <origin xyz="0 0 0" rpy="0 0 0" />

            <visual>
                <origin xyz="${track_length*0.5-track_wheel_radius+flipper_offset_x} -${track_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
                <material name="black">
                    <color rgba="1 1 1 1"/>
                </material>
            </visual>

            <visual>
                <origin xyz="0 -${track_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
                <material name="black">
                    <color rgba="1 1 1 1"/>
                </material>
            </visual>

            <visual>
                <origin xyz="${(track_length*0.5-track_wheel_radius+flipper_offset_x)*0.5} -${track_offset_y} 0.0" rpy="0 0 0"/>
                <geometry>
                    <box size="${track_length*0.5-track_wheel_radius+flipper_offset_x} ${track_width} ${track_wheel_radius*2}"/>
                </geometry>
                <material name="black">
                    <color rgba="1 1 1 1"/>
                </material>
            </visual>

            <visual>
                <origin xyz="${track_length*0.5-track_wheel_radius+flipper_offset_x} ${track_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
                <material name="black">
                    <color rgba="1 1 1 1"/>
                </material>
            </visual>

            <visual>
                <origin xyz="0 ${track_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 1"/>
                </material>
            </visual>

            <visual>
                <origin xyz="${(track_length*0.5-track_wheel_radius+flipper_offset_x)*0.5} ${track_offset_y} 0.0" rpy="0 0 0"/>
                <geometry>
                    <box size="${track_length*0.5-track_wheel_radius+flipper_offset_x} ${track_width} ${track_wheel_radius*2}"/>
                </geometry>
                <material name="black">
                    <color rgba="0 0 0 1"/>
                </material>
            </visual>


            <collision>
                <origin xyz="${track_length*0.5-track_wheel_radius+flipper_offset_x} -${track_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
            </collision>

            <collision>
                <origin xyz="0 -${track_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
            </collision>

            <collision>
                <origin xyz="${(track_length*0.5-track_wheel_radius+flipper_offset_x)*0.5} -${track_offset_y} 0.0" rpy="0 0 0"/>
                <geometry>
                    <box size="${track_length*0.5-track_wheel_radius+flipper_offset_x} ${track_width} ${track_wheel_radius*2}"/>
                </geometry>
            </collision>

            <collision>
                <origin xyz="${track_length*0.5-track_wheel_radius+flipper_offset_x} ${track_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
            </collision>

            <collision>
                <origin xyz="0 ${track_offset_y} 0.0" rpy="${M_PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${track_width}" radius="${track_wheel_radius}"/>
                </geometry>
            </collision>

            <collision>
                <origin xyz="${(track_length*0.5-track_wheel_radius+flipper_offset_x)*0.5} ${track_offset_y} 0.0" rpy="0 0 0"/>
                <geometry>
                    <box size="${track_length*0.5-track_wheel_radius+flipper_offset_x} ${track_width} ${track_wheel_radius*2}"/>
                </geometry>
            </collision>
        </link>
    </xacro:macro> 
</robot>
