gazebo_ros_control:
  pid_gains:
    flipper_joint:
      p: 2000.0
      i: 160.0
      d: 20.0
    flipper_joint_1:
      p: 2000.0
      i: 160.0
      d: 20.0

flipper_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - flipper_joint

flipper_joint_position_controller:
  type: "position_controllers/JointPositionController"
  joint: flipper_joint
