gazebo_ros_control:
  pid_gains:
    arm_joint_1:
      p: 4000.0
      i: 0.0
      d: 3.0
    arm_joint_2:
      p: 4000.0
      i: 0.0
      d: 3.0
    arm_joint_3:
      p: 4000.0
      i: 0.0
      d: 3.0
    arm_joint_4:
      p: 4000.0
      i: 0.0
      d: 3.0

arm_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - arm_joint_1
    - arm_joint_2
    - arm_joint_3
    - arm_joint_4

  allow_partial_joints_goal: true
  constraints:
    goal_time: 1.0 # Time tolerance

# Position controllers for the individual joints
# (they only forward the value from their command topic
# to the joint), not started by default, but useful
# for debugging.

arm_joint_1_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint_1

arm_joint_2_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint_2

arm_joint_3_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint_3

arm_joint_4_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint_4
