# Robot observation sources used by local planner for updating costmaps
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: velodyne, data_type: LaserScan, topic: scan, marking: true, clearing: true, expected_update_rate: 5}
